name: Deploy Hexo to GitHub Pages

on:
  push:
    paths:
      - 'source/_posts/**'  # 仅当文章文件夹有改动时触发
      - '_config.yml'       # 如果配置文件改了也重新部署
      - 'themes/**'         # 主题改动也触发部署
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Install Hexo CLI and Deployer
        run: |
          npm install hexo-cli -g
          npm install hexo-deployer-git --save

      - name: Generate Static Files
        run: |
          hexo clean
          hexo generate

      - name: Deploy to GitHub Pages
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          cd public
          git init
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Deploy Hexo site - $(date +'%Y-%m-%d %H:%M:%S')"
          git push --force https://${{ secrets.GH_TOKEN }}@github.com/Mr-liu-cheng/mr-liu-cheng.github.io.git master:gh-pages
