name: Auto Deploy Hexo

on:
  push:
    branches: [ master ]  # 监听网页提交的分支
  workflow_dispatch:    # 保留手动触发选项

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 拉取代码（关键修改点）
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 必须！获取完整提交历史

      # 2. 设置Node环境
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 3. 安装依赖（保持你的原有配置）
      - name: Install Dependencies
        run: |
          npm install
          npm install hexo-deployer-git --save
          npm install hexo-cli -g

      # 4. 生成静态文件
      - name: Generate
        run: |
          hexo clean
          hexo generate

      # 5. 自动部署（优化版）
      - name: Deploy
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 改用自动生成的token
        run: |
          cd public
          git init
          git add -A
          git commit -m "Deploy from GitHub Actions"
          git push --force "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" main:gh-pages
