name: Deploy Hexo Blog to GitHub Pages

on:
  push:
    branches:
      - master  # 你是用 master 而不是 main 分支

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Hexo CLI
        run: npm install -g hexo-cli

      - name: Install dependencies
        run: npm install
        working-directory: blog

      - name: Clean old files
        run: hexo clean
        working-directory: blog

      - name: Generate static files
        run: hexo generate
        working-directory: blog

      - name: List public output
        run: ls -R blog/public

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./blog/public
