name: Deploy Hexo Blog to GitHub Pages

on:
  push:
    branches:
      - master  # 当你推送到 master 分支时触发构建

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Hexo CLI
        run: npm install -g hexo-cli

      #- name: Setup working directory
       # run: cd blog
        #working-directory: blog

      - name: Install dependencies
        run: npm install
        working-directory: blog

      - name: Generate static files
        run: hexo generate

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
